[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or 9.
name = "AythirDreams"
# The game's title. This will show up in the title bar of your executable.
title = "Aythir Dreams"
version = "0.666.0"
authors = ["Matt Kelly <matthew.ryan.kelly@gmail.com>"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "2.2.4"
edition = "standard"

[dependencies]
maw = "1.4.1"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "aythir_dreams"
# Your username on Itch.io.
username = "mathisto"
